#!/bin/bash

set -e

git submodule update --init

./start-nodes

chmod 0600 vagrant_private_key
ansible-playbook -v --timeout 30 openstack.yaml

echo
echo "The dashboard should be at http://10.0.10.10/horizon"

