
Vagrant::Config.run do |config|

  config.vm.box = "precise64"
  
  # use a faster mirror - better in europe anyway
  config.vm.provision :shell,
    :inline => "sed -i 's/us.archive.ubuntu.com/mirror.sov.uk.goscomb.net/g' /etc/apt/sources.list"
    
  config.vm.define :controller do |controller_config|
    controller_config.vm.host_name = "controller"
    controller_config.vm.customize ["modifyvm", :id, "--memory", 1024]
    controller_config.vm.network :hostonly, "10.0.10.10" # eth1 mgt
    controller_config.vm.network :hostonly, "192.168.10.10" # eth2 tenant api
  end

  config.vm.define :netnode do |netnode_config|
    netnode_config.vm.host_name = "netnode"
    netnode_config.vm.customize ["modifyvm", :id, "--memory", 512]
    netnode_config.vm.network :hostonly, "10.0.10.11" # eth1 mgt
    netnode_config.vm.network :hostonly, "10.0.20.11" # eth2 vm traffic
    netnode_config.vm.network :hostonly, "192.168.101.101", :auto_config => false # eth3 provider net
    netnode_config.vm.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"] # eth3
    netnode_config.vm.provision :shell, :inline => "sudo ip link set dev eth3 up"
  end

  config.vm.define :compute1 do |compute1_config|
    compute1_config.vm.host_name = "compute1"
    compute1_config.vm.customize ["modifyvm", :id, "--memory", 1024]
    compute1_config.vm.network :hostonly, "10.0.10.12" # eth1 mgt
    compute1_config.vm.network :hostonly, "10.0.20.12" # eth2 vm traffic
  end

end
