---
- name: Neutron network service with the ML2 plugin
  hosts: controller
  sudo: True
  tasks:

  - name: install the neutron server package
    apt: pkg=neutron-server

    name: configure ml2 as the default plugin
  - copy: content='NEUTRON_PLUGIN_CONFIG="/etc/neutron/plugins/ml2/ml2_conf.ini"'
          dest=/etc/default/neutron-server
          owner=root group=root mode=644 backup=yes

  - name: ensure a database named neutron is present
    mysql_db: name=neutron

  - name: ensure a mysql database user named neutron is present
    mysql_user: name=neutron host={{ item }} password={{neutron_db_password }} priv=neutron.*:ALL
    with_items:
      - localhost
      - '{{ controller_ip }}'

  - name: ensure neutron.conf is configured to use the ML2 plugin and the neutron db
    template: >
          src=templates/etc/neutron/neutron.conf.j2
          dest=/etc/neutron/neutron.conf
          owner=neutron group=neutron mode=0660 backup=yes
    notify:
      - restart neutron-server

  - file: path=/etc/neutron/plugins/ml2 state=directory

  - name: ensure the ML2 plugin is configured
    template: >
          src=templates/etc/neutron/plugins/ml2/ml2_conf.ini.j2
          dest=/etc/neutron/plugins/ml2/ml2_conf.ini
          owner=neutron group=neutron mode=0660 backup=yes
    notify:
      - restart neutron-server

  handlers:
    - name: restart neutron-server
      service: name=neutron-server state=restarted
